// Copyright 2022-2026 Princess Beef Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package arazzo

// Constants for labels used to look up values within Arazzo specifications.
// https://spec.openapis.org/arazzo/v1.0.1
const (
	ArazzoLabel             = "arazzo"
	SelfLabel               = "$self"
	InfoLabel               = "info"
	SourceDescriptionsLabel = "sourceDescriptions"
	WorkflowsLabel          = "workflows"
	ComponentsLabel         = "components"
	TitleLabel              = "title"
	SummaryLabel            = "summary"
	DescriptionLabel        = "description"
	VersionLabel            = "version"
	NameLabel               = "name"
	URLLabel                = "url"
	TypeLabel               = "type"
	WorkflowIdLabel         = "workflowId"
	StepsLabel              = "steps"
	InputsLabel             = "inputs"
	DependsOnLabel          = "dependsOn"
	SuccessActionsLabel     = "successActions"
	FailureActionsLabel     = "failureActions"
	OutputsLabel            = "outputs"
	ParametersLabel         = "parameters"
	StepIdLabel             = "stepId"
	OperationIdLabel        = "operationId"
	OperationPathLabel      = "operationPath"
	ChannelPathLabel        = "channelPath"
	ActionLabel             = "action"
	CorrelationIdLabel      = "correlationId"
	TimeoutLabel            = "timeout"
	RequestBodyLabel        = "requestBody"
	SuccessCriteriaLabel    = "successCriteria"
	OnSuccessLabel          = "onSuccess"
	OnFailureLabel          = "onFailure"
	InLabel                 = "in"
	ValueLabel              = "value"
	ReferenceLabel          = "reference"
	CriteriaLabel           = "criteria"
	RetryAfterLabel         = "retryAfter"
	RetryLimitLabel         = "retryLimit"
	ContextLabel            = "context"
	ConditionLabel          = "condition"
	ContentTypeLabel        = "contentType"
	PayloadLabel            = "payload"
	ReplacementsLabel       = "replacements"
	TargetLabel             = "target"
	TargetSelectorTypeLabel = "targetSelectorType"
	SelectorLabel           = "selector"
)
