openapi: 3.1.0
info:
  version: 1.0.0
  title: Example API
  termsOfService: https://example.com/terms/
  contact:
    name: beeple
    email: contact@example.com
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  paths:
    /test:
      get:
        responses:
          "200":
            content:
              application/json:
                schema:
                  $ref: b.yaml#/components/schemas/SchemaB