// Code generated by libopenapi generator/golang. DO NOT EDIT.

package people

import "encoding/json"

type MatchConfidence string

const (
	MatchConfidenceHigh   MatchConfidence = "high"
	MatchConfidenceMedium MatchConfidence = "medium"
	MatchConfidenceLow    MatchConfidence = "low"
	MatchConfidenceNone   MatchConfidence = "none"
)

type EmploymentHistoryItem struct {
	UnderscoreID     *string         `json:"_id,omitempty"`
	CreatedAt        json.RawMessage `json:"created_at,omitempty"`
	Current          *bool           `json:"current,omitempty"`
	Degree           json.RawMessage `json:"degree,omitempty"`
	Description      json.RawMessage `json:"description,omitempty"`
	Emails           json.RawMessage `json:"emails,omitempty"`
	EndDate          json.RawMessage `json:"end_date,omitempty"`
	GradeLevel       json.RawMessage `json:"grade_level,omitempty"`
	Kind             json.RawMessage `json:"kind,omitempty"`
	Major            json.RawMessage `json:"major,omitempty"`
	OrganizationID   *string         `json:"organization_id,omitempty"`
	OrganizationName *string         `json:"organization_name,omitempty"`
	RawAddress       json.RawMessage `json:"raw_address,omitempty"`
	StartDate        *string         `json:"start_date,omitempty"`
	Title            *string         `json:"title,omitempty"`
	UpdatedAt        json.RawMessage `json:"updated_at,omitempty"`
	ID               *string         `json:"id,omitempty"`
	Key              *string         `json:"key,omitempty"`
}

type ContactEmail struct {
	Email                       *string         `json:"email,omitempty"`
	EmailMD5                    *string         `json:"email_md5,omitempty"`
	EmailSHA256                 *string         `json:"email_sha256,omitempty"`
	EmailStatus                 *string         `json:"email_status,omitempty"`
	EmailSource                 json.RawMessage `json:"email_source,omitempty"`
	ExtrapolatedEmailConfidence *float64        `json:"extrapolated_email_confidence,omitempty"`
	Position                    *int            `json:"position,omitempty"`
	EmailFromCustomer           json.RawMessage `json:"email_from_customer,omitempty"`
	FreeDomain                  *bool           `json:"free_domain,omitempty"`
}

type PhoneNumber struct {
	RawNumber       *string         `json:"raw_number,omitempty"`
	SanitizedNumber *string         `json:"sanitized_number,omitempty"`
	Type            json.RawMessage `json:"type,omitempty"`
	Position        *int            `json:"position,omitempty"`
	Status          *string         `json:"status,omitempty"`
	DncStatus       json.RawMessage `json:"dnc_status,omitempty"`
	DncOtherInfo    json.RawMessage `json:"dnc_other_info,omitempty"`
	DialerFlags     json.RawMessage `json:"dialer_flags,omitempty"`
}

type Contact struct {
	ContactRoles                    []json.RawMessage `json:"contact_roles,omitempty"`
	ID                              *string           `json:"id,omitempty"`
	FirstName                       *string           `json:"first_name,omitempty"`
	LastName                        *string           `json:"last_name,omitempty"`
	Name                            *string           `json:"name,omitempty"`
	LinkedinURL                     *string           `json:"linkedin_url,omitempty"`
	Title                           *string           `json:"title,omitempty"`
	ContactStageID                  *string           `json:"contact_stage_id,omitempty"`
	OwnerID                         json.RawMessage   `json:"owner_id,omitempty"`
	CreatorID                       *string           `json:"creator_id,omitempty"`
	PersonID                        *string           `json:"person_id,omitempty"`
	EmailNeedsTickling              json.RawMessage   `json:"email_needs_tickling,omitempty"`
	OrganizationName                *string           `json:"organization_name,omitempty"`
	Source                          *string           `json:"source,omitempty"`
	OriginalSource                  *string           `json:"original_source,omitempty"`
	OrganizationID                  *string           `json:"organization_id,omitempty"`
	Headline                        *string           `json:"headline,omitempty"`
	PhotoURL                        json.RawMessage   `json:"photo_url,omitempty"`
	PresentRawAddress               *string           `json:"present_raw_address,omitempty"`
	LinkedinUID                     json.RawMessage   `json:"linkedin_uid,omitempty"`
	ExtrapolatedEmailConfidence     *float64          `json:"extrapolated_email_confidence,omitempty"`
	SalesforceID                    json.RawMessage   `json:"salesforce_id,omitempty"`
	SalesforceLeadID                json.RawMessage   `json:"salesforce_lead_id,omitempty"`
	SalesforceContactID             json.RawMessage   `json:"salesforce_contact_id,omitempty"`
	SalesforceAccountID             json.RawMessage   `json:"salesforce_account_id,omitempty"`
	CrmOwnerID                      json.RawMessage   `json:"crm_owner_id,omitempty"`
	CreatedAt                       *string           `json:"created_at,omitempty"`
	EmailerCampaignIDs              []json.RawMessage `json:"emailer_campaign_ids,omitempty"`
	DirectDialStatus                json.RawMessage   `json:"direct_dial_status,omitempty"`
	DirectDialEnrichmentFailedAt    json.RawMessage   `json:"direct_dial_enrichment_failed_at,omitempty"`
	EmailStatus                     *string           `json:"email_status,omitempty"`
	EmailSource                     json.RawMessage   `json:"email_source,omitempty"`
	AccountID                       *string           `json:"account_id,omitempty"`
	LastActivityDate                json.RawMessage   `json:"last_activity_date,omitempty"`
	HubspotVid                      json.RawMessage   `json:"hubspot_vid,omitempty"`
	HubspotCompanyID                json.RawMessage   `json:"hubspot_company_id,omitempty"`
	CrmID                           json.RawMessage   `json:"crm_id,omitempty"`
	SanitizedPhone                  *string           `json:"sanitized_phone,omitempty"`
	MergedCrmIDs                    json.RawMessage   `json:"merged_crm_ids,omitempty"`
	UpdatedAt                       *string           `json:"updated_at,omitempty"`
	QueuedForCrmPush                json.RawMessage   `json:"queued_for_crm_push,omitempty"`
	SuggestedFromRuleEngineConfigID json.RawMessage   `json:"suggested_from_rule_engine_config_id,omitempty"`
	EmailUnsubscribed               json.RawMessage   `json:"email_unsubscribed,omitempty"`
	LabelIDs                        []json.RawMessage `json:"label_ids,omitempty"`
	HasPendingEmailArcgateRequest   *bool             `json:"has_pending_email_arcgate_request,omitempty"`
	HasEmailArcgateRequest          *bool             `json:"has_email_arcgate_request,omitempty"`
	ExistenceLevel                  *string           `json:"existence_level,omitempty"`
	Email                           *string           `json:"email,omitempty"`
	EmailFromCustomer               *bool             `json:"email_from_customer,omitempty"`
	TypedCustomFields               json.RawMessage   `json:"typed_custom_fields,omitempty"`
	CustomFieldErrors               json.RawMessage   `json:"custom_field_errors,omitempty"`
	CrmRecordURL                    json.RawMessage   `json:"crm_record_url,omitempty"`
	EmailStatusUnavailableReason    json.RawMessage   `json:"email_status_unavailable_reason,omitempty"`
	EmailTrueStatus                 *string           `json:"email_true_status,omitempty"`
	UpdatedEmailTrueStatus          *bool             `json:"updated_email_true_status,omitempty"`
	ContactRuleConfigStatuses       []json.RawMessage `json:"contact_rule_config_statuses,omitempty"`
	SourceDisplayName               *string           `json:"source_display_name,omitempty"`
	ContactEmails                   []ContactEmail    `json:"contact_emails,omitempty"`
	TimeZone                        *string           `json:"time_zone,omitempty"`
	PhoneNumbers                    []PhoneNumber     `json:"phone_numbers,omitempty"`
	AccountPhoneNote                json.RawMessage   `json:"account_phone_note,omitempty"`
	FreeDomain                      *bool             `json:"free_domain,omitempty"`
	IsLikelyToEngage                *bool             `json:"is_likely_to_engage,omitempty"`
}

type IndustryTagHash struct {
	InformationTechnologyServices *string `json:"information technology & services,omitempty"`
}

type FundingEvent struct {
	ID        *string         `json:"id,omitempty"`
	Date      *string         `json:"date,omitempty"`
	NewsURL   json.RawMessage `json:"news_url,omitempty"`
	Type      *string         `json:"type,omitempty"`
	Investors *string         `json:"investors,omitempty"`
	Amount    *string         `json:"amount,omitempty"`
	Currency  *string         `json:"currency,omitempty"`
}

type CurrentTechnology struct {
	UID      *string `json:"uid,omitempty"`
	Name     *string `json:"name,omitempty"`
	Category *string `json:"category,omitempty"`
}

type Organization struct {
	ID                           *string             `json:"id,omitempty"`
	Name                         *string             `json:"name,omitempty"`
	WebsiteURL                   *string             `json:"website_url,omitempty"`
	BlogURL                      json.RawMessage     `json:"blog_url,omitempty"`
	AngellistURL                 json.RawMessage     `json:"angellist_url,omitempty"`
	LinkedinURL                  *string             `json:"linkedin_url,omitempty"`
	TwitterURL                   *string             `json:"twitter_url,omitempty"`
	FacebookURL                  *string             `json:"facebook_url,omitempty"`
	PrimaryPhone                 json.RawMessage     `json:"primary_phone,omitempty"`
	Languages                    []json.RawMessage   `json:"languages,omitempty"`
	AlexaRanking                 *int                `json:"alexa_ranking,omitempty"`
	Phone                        json.RawMessage     `json:"phone,omitempty"`
	LinkedinUID                  *string             `json:"linkedin_uid,omitempty"`
	FoundedYear                  *int                `json:"founded_year,omitempty"`
	PubliclyTradedSymbol         json.RawMessage     `json:"publicly_traded_symbol,omitempty"`
	PubliclyTradedExchange       json.RawMessage     `json:"publicly_traded_exchange,omitempty"`
	LogoURL                      *string             `json:"logo_url,omitempty"`
	CrunchbaseURL                json.RawMessage     `json:"crunchbase_url,omitempty"`
	PrimaryDomain                *string             `json:"primary_domain,omitempty"`
	Industry                     *string             `json:"industry,omitempty"`
	Keywords                     []string            `json:"keywords,omitempty"`
	EstimatedNumEmployees        *int                `json:"estimated_num_employees,omitempty"`
	Industries                   []string            `json:"industries,omitempty"`
	SecondaryIndustries          []json.RawMessage   `json:"secondary_industries,omitempty"`
	SnippetsLoaded               *bool               `json:"snippets_loaded,omitempty"`
	IndustryTagID                *string             `json:"industry_tag_id,omitempty"`
	IndustryTagHash              *IndustryTagHash    `json:"industry_tag_hash,omitempty"`
	RetailLocationCount          *int                `json:"retail_location_count,omitempty"`
	RawAddress                   *string             `json:"raw_address,omitempty"`
	StreetAddress                *string             `json:"street_address,omitempty"`
	City                         *string             `json:"city,omitempty"`
	State                        *string             `json:"state,omitempty"`
	PostalCode                   *string             `json:"postal_code,omitempty"`
	Country                      *string             `json:"country,omitempty"`
	OwnedByOrganizationID        json.RawMessage     `json:"owned_by_organization_id,omitempty"`
	SeoDescription               *string             `json:"seo_description,omitempty"`
	ShortDescription             *string             `json:"short_description,omitempty"`
	Suborganizations             []json.RawMessage   `json:"suborganizations,omitempty"`
	NumSuborganizations          *int                `json:"num_suborganizations,omitempty"`
	AnnualRevenuePrinted         *string             `json:"annual_revenue_printed,omitempty"`
	AnnualRevenue                *int                `json:"annual_revenue,omitempty"`
	TotalFunding                 *int                `json:"total_funding,omitempty"`
	TotalFundingPrinted          *string             `json:"total_funding_printed,omitempty"`
	LatestFundingRoundDate       *string             `json:"latest_funding_round_date,omitempty"`
	LatestFundingStage           *string             `json:"latest_funding_stage,omitempty"`
	FundingEvents                []FundingEvent      `json:"funding_events,omitempty"`
	TechnologyNames              []string            `json:"technology_names,omitempty"`
	CurrentTechnologies          []CurrentTechnology `json:"current_technologies,omitempty"`
	OrgChartRootPeopleIDs        []string            `json:"org_chart_root_people_ids,omitempty"`
	OrgChartSector               *string             `json:"org_chart_sector,omitempty"`
	OrgChartRemoved              *bool               `json:"org_chart_removed,omitempty"`
	OrgChartShowDepartmentFilter *bool               `json:"org_chart_show_department_filter,omitempty"`
}

type Person struct {
	ID                          *string                 `json:"id,omitempty"`
	FirstName                   *string                 `json:"first_name,omitempty"`
	LastName                    *string                 `json:"last_name,omitempty"`
	Name                        *string                 `json:"name,omitempty"`
	LinkedinURL                 *string                 `json:"linkedin_url,omitempty"`
	Title                       *string                 `json:"title,omitempty"`
	EmailStatus                 *string                 `json:"email_status,omitempty"`
	PhotoURL                    *string                 `json:"photo_url,omitempty"`
	TwitterURL                  json.RawMessage         `json:"twitter_url,omitempty"`
	GithubURL                   json.RawMessage         `json:"github_url,omitempty"`
	FacebookURL                 json.RawMessage         `json:"facebook_url,omitempty"`
	ExtrapolatedEmailConfidence *float64                `json:"extrapolated_email_confidence,omitempty"`
	Headline                    *string                 `json:"headline,omitempty"`
	Email                       *string                 `json:"email,omitempty"`
	OrganizationID              *string                 `json:"organization_id,omitempty"`
	MatchConfidence             *MatchConfidence        `json:"match_confidence,omitempty"`
	EmploymentHistory           []EmploymentHistoryItem `json:"employment_history,omitempty"`
	State                       *string                 `json:"state,omitempty"`
	City                        *string                 `json:"city,omitempty"`
	Country                     *string                 `json:"country,omitempty"`
	ContactID                   *string                 `json:"contact_id,omitempty"`
	Contact                     *Contact                `json:"contact,omitempty"`
	RevealedForCurrentTeam      *bool                   `json:"revealed_for_current_team,omitempty"`
	Organization                *Organization           `json:"organization,omitempty"`
	IsLikelyToEngage            *bool                   `json:"is_likely_to_engage,omitempty"`
	ShowIntent                  *bool                   `json:"show_intent,omitempty"`
	Departments                 []string                `json:"departments,omitempty"`
	Subdepartments              []string                `json:"subdepartments,omitempty"`
	Functions                   []string                `json:"functions,omitempty"`
	Seniority                   *string                 `json:"seniority,omitempty"`
}

// PeopleMatchResponse is the 200 response body of [PeopleResource.Match].
type PeopleMatchResponse struct {
	// The request ID for the enrichment request. Save this ID to map this request
	// with the corresponding webhook result.
	RequestID *int    `json:"request_id,omitempty"`
	Person    *Person `json:"person,omitempty"`
}

type PeopleMatchBadRequestErrorDetails struct {
	Code        *string           `json:"code,omitempty"`
	Message     *string           `json:"message,omitempty"`
	Suggestions []json.RawMessage `json:"suggestions,omitempty"`
	Context     json.RawMessage   `json:"context,omitempty"`
}

// PeopleMatchBadRequest is the 400 response body of [PeopleResource.Match].
type PeopleMatchBadRequest struct {
	// Legacy error field. Removed on 2027-02-16, after which `error_details` is
	// the only error payload.
	//
	// Deprecated: the API marks this as deprecated.
	Error        *string                            `json:"error,omitempty"`
	ErrorDetails *PeopleMatchBadRequestErrorDetails `json:"error_details,omitempty"`
}

// PeopleMatchTooManyRequests is the 429 response body of
// [PeopleResource.Match].
type PeopleMatchTooManyRequests struct {
	ErrorDetails *ErrorDetails `json:"error_details,omitempty"`
	// Legacy error field. Removed on 2027-02-16, after which `error_details` is
	// the only error payload.
	//
	// Deprecated: the API marks this as deprecated.
	Message *string `json:"message,omitempty"`
}

type ErrorDetailsSuggestion struct {
	Label     *string `json:"label,omitempty"`
	URL       *string `json:"url,omitempty"`
	Parameter *string `json:"parameter,omitempty"`
	// Several parameters, any one of which satisfies the requirement.
	Parameters []string `json:"parameters,omitempty"`
	Header     *string  `json:"header,omitempty"`
	// A valid sample value for the parameter named above.
	Example *string `json:"example,omitempty"`
	// On a rate-limit refusal, how long to wait before retrying.
	RetryAfterSeconds *int `json:"retry_after_seconds,omitempty"`
}

type ErrorDetailsContextValue struct {
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
}

// ErrorDetails Machine-readable detail for an error that uses the new format,
// returned alongside the endpoint's existing error fields. The legacy error
// fields at the root level (`error`, `error_code`, `message`, etc) are removed
// on 2027-02-16, after which `error_details` is the only error payload. Some
// errors already return `error_details` on its own.
type ErrorDetails struct {
	// Stable identifier in the form `DOMAIN.CATEGORY.REASON`. Branch on this
	// value; the human-readable `message` can change.
	Code *string `json:"code,omitempty"`
	// Human-readable explanation of what went wrong.
	Message *string `json:"message,omitempty"`
	// Ordered, actionable next steps. Each entry carries a `label`, and where
	// relevant the `parameter`, `header`, or `url` it refers to.
	Suggestions []ErrorDetailsSuggestion `json:"suggestions,omitempty"`
	// Values from your request that explain the refusal. Each entry is an object
	// rather than a bare value, so read `context.<key>.value`. Absent when the
	// error needs no context.
	Context map[string]ErrorDetailsContextValue `json:"context,omitempty"`
}
