// Code generated by libopenapi generator/sdk/gosdk. DO NOT EDIT.

package people

import (
	"context"
	"errors"
	"net/url"
)

// PeopleResource provides operations for the People resource.
type PeopleResource struct {
	client *Client
}

// PeopleMatchParams holds the parameters for [PeopleResource.Match].
type PeopleMatchParams struct {
	// The first name of the person. This is typically used in combination with the
	// `last_name` parameter.
	//
	// Example: `jordan`
	FirstName *string

	// The last name of the person. This is typically used in combination with the
	// `first_name` parameter.
	//
	// Example: `blake`
	LastName *string

	// The full name of the person. This will typically be a first name and last
	// name separated by a space. If you use this parameter, you do not need to use
	// the `first_name` and `last_name` parameters.
	//
	// Example: `jordan blake`
	Name *string

	// The email address of the person.
	//
	// Example: `jordan@ymail.org`
	Email *string

	// The hashed email of the person. The email should adhere to either the MD5 or
	// SHA-256 hash format.
	//
	// Example: `8d935115b9ff4489f2d1f9249503cadf` (MD5) or
	// `97817c0c49994eb500ad0a5e7e2d8aed51977b26424d508f66e4e8887746a152` (SHA-256)
	HashedEmail *string

	// The name of the person's employer. This can be the current employer or a
	// previous employer.
	//
	// Example: `northstar analytics`
	OrganizationName *string

	// The domain name for the person's employer. This can be the current employer
	// or a previous employer. Do not include `www.`, the `@` symbol, or similar.
	//
	// Example: `apollo.io` or `microsoft.com`
	Domain *string

	// The Apollo ID for the person. Each person in the Apollo database is assigned
	// a unique ID.
	//
	// To find IDs, call the people API search endpoint
	// (https://docs.apollo.io/reference/people-api-search) and identify the values
	// for `person_id`.
	//
	// Example: `587cf802f65125cad923a266`
	ID *string

	// The URL for the person's LinkedIn profile.
	//
	// Example: `https://www.linkedin.com/in/jordan-blake-4a7c21`
	LinkedinURL *string

	// Set to true to enable email waterfall enrichment.
	RunWaterfallEmail *bool

	// Set to true to enable phone waterfall enrichment.
	RunWaterfallPhone *bool

	// Set to `true` if you want to enrich the person's data with personal emails.
	// This potentially consumes credits as part of your Apollo pricing plan
	// (https://docs.apollo.io/docs/api-pricing). The default value is `false`.
	//
	// If a person resides in a GDPR
	// (https://knowledge.apollo.io/hc/en-us/articles/4409141087757)-compliant
	// region, Apollo will not reveal their personal email.
	RevealPersonalEmails *bool

	// Set to `true` if you want to enrich the person's data with all available
	// phone numbers, including mobile phone numbers. This potentially consumes
	// credits as part of your Apollo pricing plan
	// (https://docs.apollo.io/docs/api-pricing). The default value is `false`.
	//
	// If this parameter is set to `true`, you must enter a webhook URL for the
	// `webhook_url` parameter. Apollo will asynchronously verify phone numbers for
	// you, then send a JSON response that includes only details about the person's
	// phone numbers to the webhook URL you provide. It can take several minutes
	// for the phone numbers to be delivered.
	RevealPhoneNumber *bool

	// If you set the `reveal_phone_number` parameter to `true`, this parameter
	// becomes mandatory. Otherwise, do not use this parameter.
	//
	// Enter the webhook URL that specifies where Apollo should send a JSON
	// response that includes the phone number you requested. Apollo suggests
	// testing this flow to ensure you receive the separate response with the phone
	// number.
	//
	// If phone numbers are not delivered to the webhook URL, try applying UTF-8
	// encoding to the webhook URL.
	//
	// Example: `https://webhook.site/11f2643a-b1b4-c6be-8e6a-6c7da2c12610`;
	// `https%3A%2F%2Fwebhook.site%2F11f2643a-b1b4-c6be-8e6a-6c7da2c12610`
	//
	// Do not use this parameter together with `poll_only=true`.
	WebhookURL *string

	// Set to `true` to receive phone or waterfall enrichment results by polling
	// instead of a webhook. When `poll_only` is `true`, omit `webhook_url` —
	// Apollo returns a `request_id` you can pass to the poll webhook result
	// (https://docs.apollo.io/reference/poll-webhook-result) endpoint to retrieve
	// the result.
	//
	// Passing `poll_only=true` together with `webhook_url` returns a `400` error
	// (`WEBHOOK_URL_WITH_POLL_ONLY`). The default value is `false`.
	PollOnly *bool
}

var securityPeopleMatch = [][]securityRequirement{
	{{Name: "apiKey"}},
	{{Name: "bearerAuth"}},
}

// Match calls POST /people/match (people-enrichment).
//
// People enrichment.
//
// A declared error response returns an [APIError] whose Value is
// *PeopleMatchBadRequest (400) or *PeopleMatchTooManyRequests (429).
func (resource *PeopleResource) Match(ctx context.Context, input *PeopleMatchParams, requestOptions ...RequestOption) (*Response[PeopleMatchResponse], error) {
	if resource == nil || resource.client == nil {
		return nil, errors.New("people-enrichment: client is required")
	}
	if input == nil {
		input = &PeopleMatchParams{}
	}
	query := make(url.Values)
	if input.FirstName != nil {
		query.Add("first_name", encodeString(*input.FirstName))
	}
	if input.LastName != nil {
		query.Add("last_name", encodeString(*input.LastName))
	}
	if input.Name != nil {
		query.Add("name", encodeString(*input.Name))
	}
	if input.Email != nil {
		query.Add("email", encodeString(*input.Email))
	}
	if input.HashedEmail != nil {
		query.Add("hashed_email", encodeString(*input.HashedEmail))
	}
	if input.OrganizationName != nil {
		query.Add("organization_name", encodeString(*input.OrganizationName))
	}
	if input.Domain != nil {
		query.Add("domain", encodeString(*input.Domain))
	}
	if input.ID != nil {
		query.Add("id", encodeString(*input.ID))
	}
	if input.LinkedinURL != nil {
		query.Add("linkedin_url", encodeString(*input.LinkedinURL))
	}
	if input.RunWaterfallEmail != nil {
		query.Add("run_waterfall_email", encodeBoolean(*input.RunWaterfallEmail))
	}
	if input.RunWaterfallPhone != nil {
		query.Add("run_waterfall_phone", encodeBoolean(*input.RunWaterfallPhone))
	}
	if input.RevealPersonalEmails != nil {
		query.Add("reveal_personal_emails", encodeBoolean(*input.RevealPersonalEmails))
	}
	if input.RevealPhoneNumber != nil {
		query.Add("reveal_phone_number", encodeBoolean(*input.RevealPhoneNumber))
	}
	if input.WebhookURL != nil {
		query.Add("webhook_url", encodeString(*input.WebhookURL))
	}
	if input.PollOnly != nil {
		query.Add("poll_only", encodeBoolean(*input.PollOnly))
	}
	request, err := resource.client.newRequest(ctx, "POST", "/people/match", query, nil, "")
	if err != nil {
		return nil, err
	}
	if err := applyRequestOptions(request, requestOptions); err != nil {
		return nil, err
	}
	response, payload, err := resource.client.do(request, securityPeopleMatch)
	if err != nil {
		return nil, err
	}
	header := response.Header.Clone()
	if response.StatusCode == 200 {
		return decodeResponse[PeopleMatchResponse](response.StatusCode, header, payload)
	}
	apiError := &APIError{StatusCode: response.StatusCode, Header: header, Body: payload}
	switch response.StatusCode {
	case 400:
		decodeErrorValue[PeopleMatchBadRequest](apiError)
	case 429:
		decodeErrorValue[PeopleMatchTooManyRequests](apiError)
	}
	return nil, apiError
}
