// Copyright 2026 Princess B33f Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package typescript

import (
	"encoding/json"
	"regexp"
	"sort"
	"strconv"
	"strings"

	highbase "github.com/pb33f/libopenapi/datamodel/high/base"
	"github.com/pb33f/libopenapi/generator/golang"
	"github.com/pb33f/libopenapi/orderedmap"
	"go.yaml.in/yaml/v4"
)

// DefaultHeaderComment is the header written at the top of every generated
// file unless WithHeaderComment replaces it.
const DefaultHeaderComment = "Code generated by libopenapi. DO NOT EDIT."

// Diagnostic codes reported by the TypeScript generator in addition to the
// shared golang IR codes.
const (
	// DiagnosticInvalidIdentifier reports a component name that is not a valid
	// TypeScript type identifier and was renamed.
	DiagnosticInvalidIdentifier = "invalidTypeScriptIdentifier"
	// DiagnosticExternalReference reports a $ref outside the document's
	// components, rendered by the name of its final path segment.
	DiagnosticExternalReference = "externalReference"
	// DiagnosticUnsupportedPointer reports a $ref into a component through a
	// keyword that has no TypeScript indexed-access equivalent.
	DiagnosticUnsupportedPointer = "unsupportedPointerReference"
)

// Diagnostic describes a notable generator decision. It is the same type the
// golang generator reports, so callers can handle both uniformly.
type Diagnostic = golang.Diagnostic

// NameResolver maps an OpenAPI component name to a TypeScript type name.
// Returning an empty string keeps the default naming.
type NameResolver func(name string) string

// Option configures a Generator.
type Option func(*Generator)

// WithHeaderComment replaces DefaultHeaderComment. Each line is written as a
// `//` comment. An empty string omits the header.
func WithHeaderComment(text string) Option {
	return func(g *Generator) {
		g.headerComment = text
	}
}

// WithTypeNameResolver sets the mapping from component names to TypeScript
// type names.
func WithTypeNameResolver(resolver NameResolver) Option {
	return func(g *Generator) {
		g.typeNameResolver = resolver
	}
}

// Generator holds immutable TypeScript generation configuration. It is safe to
// reuse across documents and goroutines.
type Generator struct {
	headerComment    string
	typeNameResolver NameResolver
}

// GeneratedFile is one TypeScript module rendered from a set of schemas.
type GeneratedFile struct {
	// Source is the complete module text.
	Source []byte
	// Types lists the exported type names in declaration order.
	Types []string
	// Diagnostics reports naming decisions made while rendering.
	Diagnostics []Diagnostic
}

// NewGenerator creates a TypeScript model generator.
func NewGenerator(opts ...Option) *Generator {
	g := &Generator{headerComment: DefaultHeaderComment}
	for _, opt := range opts {
		if opt != nil {
			opt(g)
		}
	}
	return g
}

// RenderSchemas renders an ordered map of component schemas, such as
// Components.Schemas of a v3 document, as one TypeScript module.
func RenderSchemas(schemas *orderedmap.Map[string, *highbase.SchemaProxy], opts ...Option) (*GeneratedFile, error) {
	return NewGenerator(opts...).RenderSchemas(schemas)
}

// RenderSchemas renders an ordered map of component schemas as one TypeScript
// module, declaring one exported type per schema in input order.
func (g *Generator) RenderSchemas(schemas *orderedmap.Map[string, *highbase.SchemaProxy]) (*GeneratedFile, error) {
	// The IR diagnostics describe Go model decisions (json.RawMessage unions,
	// pointer shapes) that do not apply to TypeScript, so they are not
	// forwarded; naming diagnostics are produced here.
	verbatim := func(name string) string { return name }
	irs, _, err := golang.NewGenerator(golang.WithTypeNameResolver(verbatim)).SchemaIRs(schemas)
	if err != nil {
		return nil, err
	}
	r := &render{names: make(map[string]string), components: make(map[string]*golang.SchemaIR)}
	var componentNames []string
	if schemas != nil {
		// Verbatim names claim first so a renamed component can never take the
		// name of a component that is already valid.
		registry := golang.NewNameRegistry()
		type rename struct{ component, candidate string }
		var renames []rename
		i := 0
		for name := range schemas.FromOldest() {
			componentNames = append(componentNames, name)
			r.components[name] = irs[i]
			i++
			candidate, verbatim := g.typeName(name)
			if verbatim {
				r.names[name] = r.claim(registry, name, candidate)
				continue
			}
			renames = append(renames, rename{name, candidate})
		}
		for _, rn := range renames {
			resolved := r.claim(registry, rn.component, rn.candidate)
			r.names[rn.component] = resolved
			r.diagnostics = append(r.diagnostics, Diagnostic{
				Code:    DiagnosticInvalidIdentifier,
				Path:    rn.component,
				Message: "component name is not a valid TypeScript type identifier and was rendered as " + resolved,
			})
		}
	}

	var b strings.Builder
	if g.headerComment != "" {
		for _, line := range strings.Split(g.headerComment, "\n") {
			b.WriteString(strings.TrimRight("// "+line, " "))
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	types := make([]string, 0, len(irs))
	for i, ir := range irs {
		if i > 0 {
			b.WriteString("\n")
		}
		name := r.names[componentNames[i]]
		types = append(types, name)
		r.declaration(&b, name, ir)
	}
	if len(irs) == 0 {
		b.WriteString("export {};\n")
	}
	return &GeneratedFile{Source: []byte(b.String()), Types: types, Diagnostics: r.diagnostics}, nil
}

// typeName returns the TypeScript name for a component and whether it is
// used as given (verbatim, or chosen by the resolver) rather than renamed
// because it is not a usable type identifier.
func (g *Generator) typeName(name string) (string, bool) {
	candidate := name
	if g.typeNameResolver != nil {
		if resolved := g.typeNameResolver(name); resolved != "" {
			candidate = resolved
		}
	}
	if validTypeName(candidate) {
		return candidate, true
	}
	renamed := golang.PublicName(candidate)
	if !validTypeName(renamed) {
		renamed += "Type"
	}
	return renamed, false
}

// render carries per-invocation state: resolved component names, component
// IRs for discriminator lookups, and the diagnostics recorded while printing.
type render struct {
	names       map[string]string
	components  map[string]*golang.SchemaIR
	diagnostics []Diagnostic
}

func (r *render) claim(registry *golang.NameRegistry, component, candidate string) string {
	resolved, collision := registry.Resolve(component, candidate)
	if collision {
		r.diagnostics = append(r.diagnostics, Diagnostic{
			Code:    golang.DiagnosticComponentNameCollision,
			Path:    component,
			Message: "component name collision resolved as " + resolved,
		})
	}
	return resolved
}

func (r *render) declaration(b *strings.Builder, name string, ir *golang.SchemaIR) {
	writeDoc(b, ir, "")
	if ir != nil && ir.Kind == golang.KindObject && len(ir.AllOf) == 0 && !ir.Nullable && ir.Properties != nil && ir.Properties.Len() > 0 && ir.Const == nil {
		b.WriteString("export interface " + name + " " + r.objectBody(ir, "", false) + "\n")
		return
	}
	b.WriteString("export type " + name + " = " + r.expr(ir, "") + ";\n")
}

// expr returns the TypeScript type expression for ir. indent is the
// indentation of the line the expression starts on, used for multi-line
// object literals.
func (r *render) expr(ir *golang.SchemaIR, indent string) string {
	if ir == nil {
		return "unknown"
	}
	if ir.Kind != golang.KindRef && golang.IsNullOnly(ir) {
		return "null"
	}
	if ir.Const != nil {
		if literal, ok := literalType(ir.Const); ok {
			return withNull(literal, ir.Nullable)
		}
	}
	var out string
	switch ir.Kind {
	case golang.KindRef:
		out = r.refName(ir)
	case golang.KindString:
		out = "string"
	case golang.KindInteger, golang.KindNumber:
		out = "number"
	case golang.KindBoolean:
		out = "boolean"
	case golang.KindEnum:
		out = r.enumExpr(ir)
	case golang.KindArray:
		out = arrayOf(r.expr(ir.Items, indent))
	case golang.KindObject, golang.KindAllOf:
		// The shared IR flattens allOf: inline object members merge into
		// Properties while $ref members stay in AllOf, even on KindObject.
		if len(ir.AllOf) > 0 {
			out = r.allOfExpr(ir, indent)
		} else {
			out = r.objectExpr(ir, indent)
		}
	case golang.KindUnion:
		out = r.unionExpr(ir, indent)
	default:
		return "unknown"
	}
	return withNull(out, ir.Nullable)
}

const componentSchemaPrefix = "#/components/schemas/"

func (r *render) refName(ir *golang.SchemaIR) string {
	ref := ir.Ref
	if strings.HasPrefix(ref, componentSchemaPrefix) {
		segments := strings.Split(strings.TrimPrefix(ref, componentSchemaPrefix), "/")
		for i := range segments {
			segments[i] = unescapePointer(segments[i])
		}
		if name, ok := r.names[segments[0]]; ok {
			if expr, ok := indexedAccess(name, segments[1:]); ok {
				return expr
			}
			r.diagnostics = append(r.diagnostics, Diagnostic{
				Code:    DiagnosticUnsupportedPointer,
				Path:    ref,
				Message: "reference points inside a schema through a keyword other than properties, items or additionalProperties; rendered as unknown",
			})
			return "unknown"
		}
	}
	target := golang.RefName(ref)
	if !strings.HasPrefix(ref, "#/") {
		r.diagnostics = append(r.diagnostics, Diagnostic{
			Code:    DiagnosticExternalReference,
			Path:    ref,
			Message: "external reference rendered by name as " + golang.PublicName(target),
		})
	}
	return golang.PublicName(target)
}

// indexedAccess renders a JSON pointer below a component as a TypeScript
// indexed access type, for example ConnectorDefinition/properties/connectorId
// as Exclude<NonNullable<ConnectorDefinition>["connectorId"], undefined>. Each
// container is made non-nullable so a nullable component or property can still
// be indexed. The final step excludes only the undefined an optional property
// adds: the referenced schema does not admit it, while null is kept because a
// nullable target does. It reports false for pointers through other keywords.
func indexedAccess(base string, segments []string) (string, bool) {
	if len(segments) == 0 {
		return base, true
	}
	expr := base
	for i := 0; i < len(segments); i++ {
		var index string
		switch segments[i] {
		case "properties":
			if i+1 >= len(segments) {
				return "", false
			}
			i++
			index = quote(segments[i])
		case "items":
			index = "number"
		case "additionalProperties":
			index = "string"
		default:
			return "", false
		}
		expr = "NonNullable<" + expr + ">[" + index + "]"
	}
	return "Exclude<" + expr + ", undefined>", true
}

func unescapePointer(segment string) string {
	return strings.ReplaceAll(strings.ReplaceAll(segment, "~1", "/"), "~0", "~")
}

func (r *render) enumExpr(ir *golang.SchemaIR) string {
	var values []string
	seen := make(map[string]struct{})
	nullable := ir.Nullable
	for _, node := range ir.Enum {
		literal, ok := literalType(node)
		if !ok {
			return "unknown"
		}
		if literal == "null" {
			nullable = true
			continue
		}
		if _, dup := seen[literal]; dup {
			continue
		}
		seen[literal] = struct{}{}
		values = append(values, literal)
	}
	// An enum of only null never reaches here: expr renders it as null first.
	out := strings.Join(values, " | ")
	if nullable {
		out += " | null"
	}
	return out
}

func (r *render) objectExpr(ir *golang.SchemaIR, indent string) string {
	hasProperties := ir.Properties != nil && ir.Properties.Len() > 0
	if !hasProperties {
		if ir.AdditionalProperties != nil {
			return "Record<string, " + r.expr(ir.AdditionalProperties, indent) + ">"
		}
		if ir.AdditionalAllowed != nil && !*ir.AdditionalAllowed {
			return "Record<string, never>"
		}
		return "Record<string, unknown>"
	}
	return r.objectBody(ir, indent, false)
}

// objectBody prints a braced object literal. A schema-valued or explicitly
// allowed additionalProperties adds an unknown index signature: a typed index
// signature would have to admit every declared property type as well. With
// requiredOnly, required names that have no declared property are printed as
// required unknown members; intersected with union variants that declare them,
// they make the variant's member required without changing its type.
func (r *render) objectBody(ir *golang.SchemaIR, indent string, requiredOnly bool) string {
	inner := indent + "  "
	var b strings.Builder
	b.WriteString("{\n")
	declared := make(map[string]struct{})
	if ir.Properties != nil {
		for name, prop := range ir.Properties.FromOldest() {
			declared[name] = struct{}{}
			writeDoc(&b, prop, inner)
			b.WriteString(inner + propertyKey(name))
			if !isRequired(ir, name) {
				b.WriteString("?")
			}
			b.WriteString(": " + r.expr(prop, inner) + ";\n")
		}
	}
	if requiredOnly {
		var names []string
		for name := range ir.Required {
			if _, ok := declared[name]; !ok {
				names = append(names, name)
			}
		}
		sort.Strings(names)
		for _, name := range names {
			b.WriteString(inner + propertyKey(name) + ": unknown;\n")
		}
	}
	if ir.AdditionalProperties != nil || (ir.AdditionalAllowed != nil && *ir.AdditionalAllowed) {
		b.WriteString(inner + "[key: string]: unknown;\n")
	}
	b.WriteString(indent + "}")
	return b.String()
}

func (r *render) allOfExpr(ir *golang.SchemaIR, indent string) string {
	var parts []string
	for _, child := range ir.AllOf {
		part := r.expr(child, indent)
		if child != nil && (child.Kind == golang.KindUnion || child.Kind == golang.KindEnum || child.Nullable) {
			part = "(" + part + ")"
		}
		parts = append(parts, part)
	}
	if ir.Properties != nil && ir.Properties.Len() > 0 {
		parts = append(parts, r.objectBody(ir, indent, false))
	}
	return strings.Join(parts, " & ")
}

// unionExpr prints oneOf and anyOf as a TypeScript union. Properties and
// required names declared beside the union apply to every variant, so they
// are intersected with it. When a oneOf carries a discriminator mapping, each
// referenced variant whose discriminator property is not already a literal is
// intersected with its mapped values so the union narrows on that property.
func (r *render) unionExpr(ir *golang.SchemaIR, indent string) string {
	union := ir.Union
	discriminatorValues := make(map[string][]string)
	if union.Discriminator != nil && union.Discriminator.PropertyName != "" {
		for value, target := range union.Discriminator.Mapping {
			if !strings.ContainsAny(target, "#/") {
				target = componentSchemaPrefix + target
			}
			discriminatorValues[target] = append(discriminatorValues[target], value)
		}
	}
	var parts []string
	seen := make(map[string]struct{})
	for _, variant := range union.Variants {
		part := r.expr(variant, indent)
		if variant != nil && variant.Kind == golang.KindRef {
			if values := discriminatorValues[variant.Ref]; len(values) > 0 {
				if literals, ok := r.discriminatorLiterals(variant, union.Discriminator.PropertyName, values); ok {
					part = "(" + part + " & { " + propertyKey(union.Discriminator.PropertyName) + ": " + literals + " })"
				}
			}
		}
		if _, dup := seen[part]; dup {
			continue
		}
		seen[part] = struct{}{}
		parts = append(parts, part)
	}
	out := strings.Join(parts, " | ")
	hasSiblings := (ir.Properties != nil && ir.Properties.Len() > 0) || len(ir.Required) > 0
	if !hasSiblings {
		return out
	}
	if len(parts) > 1 {
		out = "(" + out + ")"
	}
	return r.objectBody(ir, indent, true) + " & " + out
}

// discriminatorLiterals renders mapping values as literal types matching the
// variant's discriminator property. It only narrows a property the variant
// declares inline as a plain string, integer or number: a const or enum
// already narrows by itself, and a property inherited through allOf or typed
// by $ref has a type this cannot see, where a guessed literal could make the
// variant never. It also reports false when a value does not fit the type.
func (r *render) discriminatorLiterals(variant *golang.SchemaIR, property string, values []string) (string, bool) {
	target := r.components[unescapePointer(strings.TrimPrefix(variant.Ref, componentSchemaPrefix))]
	if target == nil || target.Properties == nil {
		return "", false
	}
	prop, ok := target.Properties.Get(property)
	if !ok || prop == nil || prop.Const != nil {
		return "", false
	}
	var numeric bool
	switch prop.Kind {
	case golang.KindString:
	case golang.KindInteger, golang.KindNumber:
		numeric = true
	default:
		return "", false
	}
	sort.Strings(values)
	literals := make([]string, 0, len(values))
	for _, value := range values {
		if !numeric {
			literals = append(literals, quote(value))
			continue
		}
		var number json.Number
		if err := json.Unmarshal([]byte(value), &number); err != nil {
			return "", false
		}
		literals = append(literals, number.String())
	}
	return strings.Join(literals, " | "), true
}

func writeDoc(b *strings.Builder, ir *golang.SchemaIR, indent string) {
	var lines []string
	if description := strings.TrimSpace(ir.Description); description != "" {
		lines = append(lines, strings.Split(description, "\n")...)
	}
	if ir.Deprecated {
		lines = append(lines, "@deprecated")
	}
	if len(lines) == 0 {
		return
	}
	b.WriteString(indent + "/**\n")
	for _, line := range lines {
		line = strings.ReplaceAll(strings.TrimRight(line, " \t\r"), "*/", "*\\/")
		if line == "" {
			b.WriteString(indent + " *\n")
			continue
		}
		b.WriteString(indent + " * " + line + "\n")
	}
	b.WriteString(indent + " */\n")
}

func isRequired(ir *golang.SchemaIR, name string) bool {
	_, ok := ir.Required[name]
	return ok
}

// literalType renders a scalar YAML node as a TypeScript literal type.
func literalType(node *yaml.Node) (string, bool) {
	if node == nil || node.Kind != yaml.ScalarNode {
		return "", false
	}
	switch node.Tag {
	case "!!null":
		return "null", true
	case "!!bool":
		// YAML also spells booleans True and FALSE.
		return strconv.FormatBool(strings.EqualFold(node.Value, "true")), true
	case "!!int", "!!float":
		var number json.Number
		if err := json.Unmarshal([]byte(node.Value), &number); err != nil {
			return "", false
		}
		return number.String(), true
	default:
		return quote(node.Value), true
	}
}

// quote renders a JSON string literal, which is also a valid TypeScript string
// literal, without escaping HTML characters the way json.Marshal does.
func quote(value string) string {
	var b strings.Builder
	encoder := json.NewEncoder(&b)
	encoder.SetEscapeHTML(false)
	_ = encoder.Encode(value)
	return strings.TrimSuffix(b.String(), "\n")
}

func withNull(expr string, nullable bool) string {
	if !nullable || expr == "unknown" || expr == "null" || strings.HasSuffix(expr, " | null") {
		return expr
	}
	return expr + " | null"
}

func arrayOf(element string) string {
	if identifierPattern.MatchString(element) || strings.HasPrefix(element, "Record<") && !strings.Contains(element, " | ") {
		return element + "[]"
	}
	return "Array<" + element + ">"
}

var identifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func propertyKey(name string) string {
	if identifierPattern.MatchString(name) {
		return name
	}
	return quote(name)
}

func validTypeName(name string) bool {
	if !identifierPattern.MatchString(name) {
		return false
	}
	for _, reserved := range reservedTypeNames {
		if name == reserved {
			return false
		}
	}
	return true
}

// reservedTypeNames are names a generated declaration cannot take: TypeScript
// reserved words, predefined type names, and the global generic types the
// generated output itself refers to.
var reservedTypeNames = []string{
	"any", "bigint", "boolean", "break", "case", "catch", "class", "const", "continue",
	"debugger", "declare", "default", "delete", "do", "else", "enum", "export", "extends",
	"false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof",
	"interface", "let", "never", "new", "null", "number", "object", "package", "private",
	"protected", "public", "return", "static", "string", "super", "switch", "symbol", "this",
	"throw", "true", "try", "typeof", "undefined", "unknown", "var", "void", "while", "with",
	"yield",
	"Array", "Exclude", "NonNullable", "Record",
}
