// Copyright 2026 Princess B33f Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package typescript

import (
	"encoding/json"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/pb33f/go-yaml"
	highbase "github.com/pb33f/libopenapi/datamodel/high/base"
	"github.com/pb33f/libopenapi/generator/golang"
	"github.com/pb33f/libopenapi/orderedmap"
)

// DefaultHeaderComment is the header written at the top of every generated
// file unless WithHeaderComment replaces it.
const DefaultHeaderComment = "Code generated by libopenapi. DO NOT EDIT."

// Diagnostic codes reported by the TypeScript generator in addition to the
// shared golang IR codes.
const (
	// DiagnosticInvalidIdentifier reports a component name that is not a valid
	// TypeScript type identifier and was renamed.
	DiagnosticInvalidIdentifier = "invalidTypeScriptIdentifier"
	// DiagnosticExternalReference reports a $ref outside the document's
	// components, rendered by the name of its final path segment.
	DiagnosticExternalReference = "externalReference"
	// DiagnosticUnsupportedPointer reports a $ref into a component through a
	// keyword that has no TypeScript indexed-access equivalent.
	DiagnosticUnsupportedPointer = "unsupportedPointerReference"
)

// Diagnostic describes a notable generator decision. It is the same type the
// golang generator reports, so callers can handle both uniformly.
type Diagnostic = golang.Diagnostic

// NameResolver maps an OpenAPI component name to a TypeScript type name.
// Returning an empty string keeps the default naming.
type NameResolver func(name string) string

// Option configures a Generator.
type Option func(*Generator)

// WithHeaderComment replaces DefaultHeaderComment. Each line is written as a
// `//` comment. An empty string omits the header.
func WithHeaderComment(text string) Option {
	return func(g *Generator) {
		g.headerComment = text
	}
}

// WithTypeNameResolver sets the mapping from component names to TypeScript
// type names.
func WithTypeNameResolver(resolver NameResolver) Option {
	return func(g *Generator) {
		g.typeNameResolver = resolver
	}
}

// Generator holds immutable TypeScript generation configuration. It is safe to
// reuse across documents and goroutines.
type Generator struct {
	headerComment    string
	typeNameResolver NameResolver
}

// GeneratedFile is one TypeScript module rendered from a set of schemas.
type GeneratedFile struct {
	// Source is the complete module text.
	Source []byte
	// Types lists the exported type names in declaration order.
	Types []string
	// Diagnostics reports naming decisions, pointers and schema keywords that
	// could not be rendered exactly, and nested schemas that could not be built.
	Diagnostics []Diagnostic
}

// NewGenerator creates a TypeScript model generator.
func NewGenerator(opts ...Option) *Generator {
	g := &Generator{headerComment: DefaultHeaderComment}
	for _, opt := range opts {
		if opt != nil {
			opt(g)
		}
	}
	return g
}

// RenderSchemas renders an ordered map of component schemas, such as
// Components.Schemas of a v3 document, as one TypeScript module.
func RenderSchemas(schemas *orderedmap.Map[string, *highbase.SchemaProxy], opts ...Option) (*GeneratedFile, error) {
	return NewGenerator(opts...).RenderSchemas(schemas)
}

// RenderSchemas renders an ordered map of component schemas as one TypeScript
// module, declaring one exported type per schema in input order.
func (g *Generator) RenderSchemas(schemas *orderedmap.Map[string, *highbase.SchemaProxy]) (*GeneratedFile, error) {
	irs, irDiagnostics, err := golang.NewGenerator(golang.WithTypeNameResolver(verbatim)).SchemaIRs(schemas)
	if err != nil {
		return nil, err
	}
	r := &render{names: make(map[string]string), components: make(map[string]*golang.SchemaIR), siblings: make(map[*golang.SchemaIR]*orderedmap.Map[string, *golang.SchemaIR])}
	r.forwardChildSchemaDiagnostics(irDiagnostics)
	var componentNames []string
	if schemas != nil {
		// Verbatim names claim first so a renamed component can never take the
		// name of a component that is already valid.
		registry := golang.NewNameRegistry()
		type rename struct{ component, candidate string }
		var renames []rename
		i := 0
		for name := range schemas.FromOldest() {
			componentNames = append(componentNames, name)
			r.components[name] = irs[i]
			i++
			candidate, kept := g.typeName(name)
			if kept {
				r.names[name] = r.claim(registry, name, candidate)
				continue
			}
			renames = append(renames, rename{name, candidate})
		}
		for _, rn := range renames {
			resolved := r.claim(registry, rn.component, rn.candidate)
			r.names[rn.component] = resolved
			r.diagnostics = append(r.diagnostics, Diagnostic{
				Code:    DiagnosticInvalidIdentifier,
				Path:    rn.component,
				Message: "component name is not a valid TypeScript type identifier and was rendered as " + resolved,
			})
		}
	}

	var b strings.Builder
	if g.headerComment != "" {
		for _, line := range strings.Split(g.headerComment, "\n") {
			b.WriteString(strings.TrimRight("// "+line, " "))
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	types := make([]string, 0, len(irs))
	for i, ir := range irs {
		if i > 0 {
			b.WriteString("\n")
		}
		name := r.names[componentNames[i]]
		types = append(types, name)
		r.declaration(&b, name, ir)
	}
	if len(irs) == 0 {
		b.WriteString("export {};\n")
	}
	return &GeneratedFile{Source: []byte(b.String()), Types: types, Diagnostics: r.diagnostics}, nil
}

// typeName returns the TypeScript name for a component and whether it is
// used as given (verbatim, or chosen by the resolver) rather than renamed
// because it is not a usable type identifier.
func (g *Generator) typeName(name string) (string, bool) {
	candidate := name
	if g.typeNameResolver != nil {
		if resolved := g.typeNameResolver(name); resolved != "" {
			candidate = resolved
		}
	}
	if validTypeName(candidate) {
		return candidate, true
	}
	renamed := golang.PublicName(candidate)
	if !validTypeName(renamed) {
		renamed += "Type"
	}
	return renamed, false
}

// verbatim keeps names exactly as the document spells them when the golang IR
// builder names types.
func verbatim(name string) string { return name }

// render carries per-invocation state: resolved component names, component
// IRs for discriminator lookups, and the diagnostics recorded while printing.
type render struct {
	names       map[string]string
	components  map[string]*golang.SchemaIR
	siblings    map[*golang.SchemaIR]*orderedmap.Map[string, *golang.SchemaIR]
	diagnostics []Diagnostic
}

// forwardChildSchemaDiagnostics keeps the IR diagnostics that apply to
// TypeScript. Most describe Go model decisions (json.RawMessage unions,
// pointer depth); a nested schema that could not be built renders as unknown
// here too, so that one is kept.
func (r *render) forwardChildSchemaDiagnostics(diagnostics []Diagnostic) {
	for _, d := range diagnostics {
		if d.Code == golang.DiagnosticChildSchema {
			d.Message = strings.Replace(d.Message, "rendered as any", "rendered as unknown", 1)
			r.diagnostics = append(r.diagnostics, d)
		}
	}
}

func (r *render) claim(registry *golang.NameRegistry, component, candidate string) string {
	resolved, collision := registry.Resolve(component, candidate)
	if collision {
		r.diagnostics = append(r.diagnostics, Diagnostic{
			Code:    golang.DiagnosticComponentNameCollision,
			Path:    component,
			Message: "component name collision resolved as " + resolved,
		})
	}
	return resolved
}

func (r *render) declaration(b *strings.Builder, name string, ir *golang.SchemaIR) {
	writeDoc(b, ir, "")
	if ir != nil && ir.Kind == golang.KindObject && len(ir.AllOf) == 0 && !ir.Nullable && ir.Properties != nil && ir.Properties.Len() > 0 && ir.Const == nil {
		b.WriteString("export interface " + name + " " + r.objectBody(ir, "", false) + "\n")
		return
	}
	b.WriteString("export type " + name + " = " + r.expr(ir, "") + ";\n")
}

// expr returns the TypeScript type expression for ir. indent is the
// indentation of the line the expression starts on, used for multi-line
// object literals.
func (r *render) expr(ir *golang.SchemaIR, indent string) string {
	if ir == nil {
		return "unknown"
	}
	if ir.Kind != golang.KindRef && golang.IsNullOnly(ir) {
		return "null"
	}
	if ir.Const != nil {
		if literal, ok := literalType(ir.Const); ok {
			return withNull(literal, ir.Nullable && !nullExcluded(ir))
		}
	}
	var out string
	switch ir.Kind {
	case golang.KindRef:
		out = r.refName(ir, indent)
	case golang.KindString:
		out = "string"
	case golang.KindInteger, golang.KindNumber:
		out = "number"
	case golang.KindBoolean:
		out = "boolean"
	case golang.KindEnum:
		out = r.enumExpr(ir)
	case golang.KindArray:
		out = r.arrayExpr(ir, indent)
	case golang.KindObject, golang.KindAllOf:
		// The shared IR flattens allOf: inline object members merge into
		// Properties while $ref members stay in AllOf, even on KindObject.
		if len(ir.AllOf) > 0 {
			out = r.allOfExpr(ir, indent)
		} else {
			out = r.objectExpr(ir, indent)
		}
	case golang.KindUnion:
		out = r.unionExpr(ir, indent)
	default:
		return "unknown"
	}
	return withNull(out, ir.Nullable && !nullExcluded(ir))
}

const componentSchemaPrefix = "#/components/schemas/"

func (r *render) refName(ir *golang.SchemaIR, indent string) string {
	ref := ir.Ref
	if strings.HasPrefix(ref, componentSchemaPrefix) {
		segments := strings.Split(strings.TrimPrefix(ref, componentSchemaPrefix), "/")
		for i := range segments {
			segments[i] = unescapePointer(segments[i])
		}
		if name, ok := r.names[segments[0]]; ok {
			if len(segments) == 1 {
				return name
			}
			if target, ok := r.pointerTarget(r.components[segments[0]], segments[1:]); ok {
				return r.expr(target, indent)
			}
			r.diagnostics = append(r.diagnostics, Diagnostic{
				Code:    DiagnosticUnsupportedPointer,
				Path:    ref,
				Message: "reference points inside a schema to something other than a declared property, items or additionalProperties schema; rendered as unknown",
			})
			return "unknown"
		}
	}
	target := golang.RefName(ref)
	if !strings.HasPrefix(ref, "#/") {
		r.diagnostics = append(r.diagnostics, Diagnostic{
			Code:    DiagnosticExternalReference,
			Path:    ref,
			Message: "external reference rendered by name as " + golang.PublicName(target),
		})
	}
	return golang.PublicName(target)
}

// pointerTarget walks a JSON pointer below a component through the IR and
// returns the schema it names, so the reference renders as that schema's own
// type rather than as an indexed access into its container (which would lose
// the value type behind an index signature). libopenapi only resolves pointers
// through literal schema keywords, never through a $ref, so the walk does not
// follow references. It reports false for keywords other than properties,
// items and additionalProperties, or when the IR does not carry the schema.
func (r *render) pointerTarget(ir *golang.SchemaIR, segments []string) (*golang.SchemaIR, bool) {
	for i := 0; i < len(segments) && ir != nil; i++ {
		switch segments[i] {
		case "properties":
			if i+1 >= len(segments) {
				return nil, false
			}
			i++
			ir, _ = r.properties(ir).Get(segments[i])
		case "items":
			ir = ir.Items
		case "additionalProperties":
			ir = ir.AdditionalProperties
		default:
			return nil, false
		}
	}
	return ir, ir != nil
}

func unescapePointer(segment string) string {
	return strings.ReplaceAll(strings.ReplaceAll(segment, "~1", "/"), "~0", "~")
}

func (r *render) enumExpr(ir *golang.SchemaIR) string {
	var values []string
	seen := make(map[string]struct{})
	nullable := ir.Nullable && !nullExcluded(ir)
	for _, node := range ir.Enum {
		literal, ok := literalType(node)
		if !ok {
			return "unknown"
		}
		if literal == "null" {
			nullable = true
			continue
		}
		if _, dup := seen[literal]; dup {
			continue
		}
		seen[literal] = struct{}{}
		values = append(values, literal)
	}
	// An enum of only null never reaches here: expr renders it as null first.
	out := strings.Join(values, " | ")
	if nullable {
		out += " | null"
	}
	return out
}

// nullExcluded reports a 3.1 schema whose type array admits null while its
// enum or const does not, so null is not a valid value. OpenAPI 3.0 nullable
// adds null regardless, and a nullable oneOf collapsed onto one variant keeps
// the variant's schema, whose type array does not name null.
func nullExcluded(ir *golang.SchemaIR) bool {
	schema := ir.SourceSchema
	if schema == nil || !slices.Contains(schema.Type, "null") || (schema.Nullable != nil && *schema.Nullable) {
		return false
	}
	if schema.Const != nil {
		return !isNullNode(schema.Const)
	}
	return len(schema.Enum) > 0 && !slices.ContainsFunc(schema.Enum, isNullNode)
}

func isNullNode(node *yaml.Node) bool {
	return node != nil && node.Tag == "!!null"
}

// arrayExpr renders items as an element type and 3.1 prefixItems as a tuple.
// Prefix positions are optional because JSON Schema does not require an array
// to reach them; items then types the rest, items: false closes the tuple, and
// no items leaves the rest unknown.
func (r *render) arrayExpr(ir *golang.SchemaIR, indent string) string {
	if len(ir.PrefixItems) == 0 {
		return arrayOf(r.expr(ir.Items, indent))
	}
	elements := make([]string, 0, len(ir.PrefixItems)+1)
	for _, prefix := range ir.PrefixItems {
		elements = append(elements, parenthesizeUnion(r.expr(prefix, indent))+"?")
	}
	closed := ir.SourceSchema != nil && ir.SourceSchema.Items != nil && ir.SourceSchema.Items.IsB() && !ir.SourceSchema.Items.B
	if !closed {
		elements = append(elements, "..."+arrayOf(r.expr(ir.Items, indent)))
	}
	return "[" + strings.Join(elements, ", ") + "]"
}

// objectExpr renders an object. Maps are written as index-signature literals
// rather than Record<string, T>: a type alias may refer to itself through an
// object literal but not through Record, so recursive maps such as a JSON value
// type would not compile.
func (r *render) objectExpr(ir *golang.SchemaIR, indent string) string {
	if r.properties(ir).Len() > 0 || len(ir.Required) > 0 {
		return r.objectBody(ir, indent, false)
	}
	switch {
	case hasPatternProperties(ir):
		return "{ [key: string]: unknown }"
	case ir.AdditionalProperties != nil:
		return "{ [key: string]: " + r.expr(ir.AdditionalProperties, indent) + " }"
	case ir.AdditionalAllowed != nil && !*ir.AdditionalAllowed:
		return "{ [key: string]: never }"
	}
	return "{ [key: string]: unknown }"
}

// properties returns the declared properties of ir. For an object built from
// allOf that also declares properties beside it, the shared IR keeps only the
// members' properties, so the sibling ones are built here and appended.
func (r *render) properties(ir *golang.SchemaIR) *orderedmap.Map[string, *golang.SchemaIR] {
	if cached, ok := r.siblings[ir]; ok {
		return cached
	}
	props := orderedmap.New[string, *golang.SchemaIR]()
	if ir.Properties != nil {
		for name, prop := range ir.Properties.FromOldest() {
			props.Set(name, prop)
		}
	}
	if schema := ir.SourceSchema; schema != nil && len(schema.AllOf) > 0 && schema.Properties != nil && schema.Properties.Len() > 0 {
		siblings, diagnostics, err := golang.NewGenerator(golang.WithTypeNameResolver(verbatim)).SchemaIRs(schema.Properties)
		r.forwardChildSchemaDiagnostics(diagnostics)
		if err != nil {
			r.diagnostics = append(r.diagnostics, Diagnostic{
				Code:    golang.DiagnosticChildSchema,
				Path:    ir.Name,
				Message: "properties declared beside allOf could not be built and were left out: " + err.Error(),
			})
			siblings = nil
		}
		for i, name := range slices.Collect(schema.Properties.KeysFromOldest()) {
			if _, declared := props.Get(name); !declared && i < len(siblings) {
				props.Set(name, siblings[i])
			}
		}
	}
	r.siblings[ir] = props
	return props
}

func hasPatternProperties(ir *golang.SchemaIR) bool {
	return ir.PatternProperties != nil && ir.PatternProperties.Len() > 0
}

// objectBody prints a braced object literal. Required names that have no
// declared property are still required members: they take the
// additionalProperties schema when there is one, and unknown otherwise. Beside
// a union (unionSiblings) they are always unknown, so that intersected with a
// variant that declares the name they make it required without changing its
// type. An additionalProperties schema becomes a typed index signature when
// every member takes that type, and an unknown one otherwise, because an index
// signature must admit every declared property's type; an explicit
// additionalProperties: true also adds the unknown signature.
func (r *render) objectBody(ir *golang.SchemaIR, indent string, unionSiblings bool) string {
	inner := indent + "  "
	var b strings.Builder
	b.WriteString("{\n")
	declared := make(map[string]struct{})
	for name, prop := range r.properties(ir).FromOldest() {
		declared[name] = struct{}{}
		writeDoc(&b, prop, inner)
		b.WriteString(inner + propertyKey(name))
		if !isRequired(ir, name) {
			b.WriteString("?")
		}
		b.WriteString(": " + r.expr(prop, inner) + ";\n")
	}
	undeclaredType := "unknown"
	if ir.AdditionalProperties != nil && !unionSiblings {
		undeclaredType = r.expr(ir.AdditionalProperties, inner)
	}
	var names []string
	for name := range ir.Required {
		if _, ok := declared[name]; !ok {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(inner + propertyKey(name) + ": " + undeclaredType + ";\n")
	}
	switch {
	case hasPatternProperties(ir):
		b.WriteString(inner + "[key: string]: unknown;\n")
	case ir.AdditionalProperties != nil && len(declared) == 0 && !unionSiblings:
		b.WriteString(inner + "[key: string]: " + undeclaredType + ";\n")
	case ir.AdditionalProperties != nil || (ir.AdditionalAllowed != nil && *ir.AdditionalAllowed):
		b.WriteString(inner + "[key: string]: unknown;\n")
	}
	b.WriteString(indent + "}")
	return b.String()
}

// allOfExpr intersects the referenced members with an object literal of the
// merged inline members. Required names with no declared property, such as a
// member that only makes an inherited property required, are printed as
// unknown so the intersection makes the inherited member required without
// changing its type. A member that renders as unknown adds nothing and is
// left out.
func (r *render) allOfExpr(ir *golang.SchemaIR, indent string) string {
	var parts []string
	for _, child := range ir.AllOf {
		part := r.expr(child, indent)
		if part == "unknown" {
			continue
		}
		parts = append(parts, parenthesizeUnion(part))
	}
	if r.properties(ir).Len() > 0 || len(ir.Required) > 0 {
		parts = append(parts, r.objectBody(ir, indent, true))
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(parts, " & ")
}

// unionExpr prints oneOf and anyOf as a TypeScript union. Properties and
// required names declared beside the union apply to every variant, so they
// are intersected with it. When a oneOf carries a discriminator mapping, each
// referenced variant whose discriminator property is not already a literal is
// intersected with its mapped values so the union narrows on that property.
func (r *render) unionExpr(ir *golang.SchemaIR, indent string) string {
	union := ir.Union
	discriminatorValues := make(map[string][]string)
	if union.Discriminator != nil && union.Discriminator.PropertyName != "" {
		for value, target := range union.Discriminator.Mapping {
			if !strings.ContainsAny(target, "#/") {
				target = componentSchemaPrefix + target
			}
			discriminatorValues[target] = append(discriminatorValues[target], value)
		}
	}
	var parts []string
	seen := make(map[string]struct{})
	for _, variant := range union.Variants {
		part := r.expr(variant, indent)
		if union.Discriminator != nil && variant.Kind == golang.KindRef {
			// OpenAPI falls back to the schema name when no mapping entry
			// matches, so the name is accepted alongside any mapped values.
			values := append([]string{golang.RefName(variant.Ref)}, discriminatorValues[variant.Ref]...)
			if literals, ok := r.discriminatorLiterals(variant, union.Discriminator.PropertyName, values); ok {
				part = "(" + part + " & { " + propertyKey(union.Discriminator.PropertyName) + ": " + literals + " })"
			}
		}
		if _, dup := seen[part]; dup {
			continue
		}
		seen[part] = struct{}{}
		parts = append(parts, part)
	}
	out := strings.Join(parts, " | ")
	hasSiblings := (ir.Properties != nil && ir.Properties.Len() > 0) || len(ir.Required) > 0
	if !hasSiblings {
		return out
	}
	return r.objectBody(ir, indent, true) + " & " + parenthesizeUnion(out)
}

// discriminatorLiterals renders mapping values as literal types matching the
// variant's discriminator property. It only narrows a property the variant
// declares inline as a plain string, integer or number: a const or enum
// already narrows by itself, and a property inherited through allOf or typed
// by $ref has a type this cannot see, where a guessed literal could make the
// variant never. It also reports false when a value does not fit the type.
func (r *render) discriminatorLiterals(variant *golang.SchemaIR, property string, values []string) (string, bool) {
	target := r.components[unescapePointer(strings.TrimPrefix(variant.Ref, componentSchemaPrefix))]
	if target == nil || target.Properties == nil {
		return "", false
	}
	prop, ok := target.Properties.Get(property)
	if !ok || prop == nil || prop.Const != nil {
		return "", false
	}
	var numeric bool
	switch prop.Kind {
	case golang.KindString:
	case golang.KindInteger, golang.KindNumber:
		numeric = true
	default:
		return "", false
	}
	sort.Strings(values)
	var literals []string
	for _, value := range values {
		literal := quote(value)
		if numeric {
			var number json.Number
			if json.Unmarshal([]byte(value), &number) != nil {
				continue // the schema name, or a key that is not a number
			}
			literal = number.String()
		}
		if !slices.Contains(literals, literal) {
			literals = append(literals, literal)
		}
	}
	if len(literals) == 0 {
		return "", false
	}
	return strings.Join(literals, " | "), true
}

func writeDoc(b *strings.Builder, ir *golang.SchemaIR, indent string) {
	var lines []string
	if description := strings.TrimSpace(ir.Description); description != "" {
		lines = append(lines, strings.Split(description, "\n")...)
	}
	if ir.Deprecated {
		lines = append(lines, "@deprecated")
	}
	if len(lines) == 0 {
		return
	}
	b.WriteString(indent + "/**\n")
	for _, line := range lines {
		line = strings.ReplaceAll(strings.TrimRight(line, " \t\r"), "*/", "*\\/")
		if line == "" {
			b.WriteString(indent + " *\n")
			continue
		}
		b.WriteString(indent + " * " + line + "\n")
	}
	b.WriteString(indent + " */\n")
}

func isRequired(ir *golang.SchemaIR, name string) bool {
	_, ok := ir.Required[name]
	return ok
}

// literalType renders a scalar YAML node as a TypeScript literal type.
func literalType(node *yaml.Node) (string, bool) {
	if node == nil || node.Kind != yaml.ScalarNode {
		return "", false
	}
	switch node.Tag {
	case "!!null":
		return "null", true
	case "!!bool":
		// YAML also spells booleans True and FALSE.
		return strconv.FormatBool(strings.EqualFold(node.Value, "true")), true
	case "!!int", "!!float":
		var number json.Number
		if err := json.Unmarshal([]byte(node.Value), &number); err != nil {
			return "", false
		}
		return number.String(), true
	default:
		return quote(node.Value), true
	}
}

// quote renders a JSON string literal, which is also a valid TypeScript string
// literal, without escaping HTML characters the way json.Marshal does.
func quote(value string) string {
	var b strings.Builder
	encoder := json.NewEncoder(&b)
	encoder.SetEscapeHTML(false)
	_ = encoder.Encode(value)
	return strings.TrimSuffix(b.String(), "\n")
}

func withNull(expr string, nullable bool) string {
	if !nullable || expr == "unknown" || expr == "null" || strings.HasSuffix(expr, " | null") {
		return expr
	}
	return expr + " | null"
}

func arrayOf(element string) string {
	if identifierPattern.MatchString(element) {
		return element + "[]"
	}
	return "Array<" + element + ">"
}

// parenthesizeUnion wraps an expression whose top level is a union so it keeps
// its meaning inside an intersection or tuple. A " | " nested inside braces,
// brackets, parentheses, angle brackets or a string literal does not count.
func parenthesizeUnion(expr string) string {
	depth := 0
	inString := false
	for i := 0; i < len(expr); i++ {
		c := expr[i]
		switch {
		case inString:
			if c == '\\' {
				i++
			} else if c == '"' {
				inString = false
			}
		case c == '"':
			inString = true
		case strings.IndexByte("{[(<", c) >= 0:
			depth++
		case strings.IndexByte("}])>", c) >= 0:
			depth--
		case depth == 0 && strings.HasPrefix(expr[i:], " | "):
			return "(" + expr + ")"
		}
	}
	return expr
}

var identifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func propertyKey(name string) string {
	if identifierPattern.MatchString(name) {
		return name
	}
	return quote(name)
}

func validTypeName(name string) bool {
	if !identifierPattern.MatchString(name) {
		return false
	}
	for _, reserved := range reservedTypeNames {
		if name == reserved {
			return false
		}
	}
	return true
}

// reservedTypeNames are names a generated declaration cannot take: TypeScript
// reserved words, predefined type names, and the global generic types the
// generated output itself refers to.
var reservedTypeNames = []string{
	"any", "as", "await", "bigint", "boolean", "break", "case", "catch", "class", "const", "continue",
	"debugger", "default", "delete", "do", "else", "enum", "export", "extends",
	"false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof",
	"interface", "let", "never", "new", "null", "number", "object", "package", "private",
	"protected", "public", "return", "static", "string", "super", "switch", "symbol", "this",
	"throw", "true", "try", "typeof", "undefined", "unknown", "var", "void", "while", "with",
	"yield",
	"Array",
}
