// Code generated by libopenapi. DO NOT EDIT.

/**
 * An account.
 * Second line with a *\/ comment terminator.
 */
export interface Account {
  id: string;
  name: string;
  seats?: number;
  score?: number | null;
  active?: boolean;
  tags: string[];
  owner?: Person;
  status?: Status;
  /**
   * @deprecated
   */
  legacyCode?: string;
  "content-type"?: string;
  address?: {
    line1: string;
    city?: string;
  };
  history?: Array<Person | string>;
}

export interface Person {
  name: string;
}

export type Status = "active" | "paused" | "closed";

export type NullableStatus = "on" | "off" | null;

export type Priority = 1 | 2 | 3;

export type Labels = { [key: string]: string };

export interface Extensible {
  kind: string;
  [key: string]: unknown;
}

export type Opaque = { [key: string]: unknown };

export type AnyValue = unknown;

export type Admin = Person & {
  level: number;
};

export type PersonAlias = Person;

export type Pet = (Cat & { petType: "Cat" | "cat" | "kitten" }) | (Dog & { petType: "Dog" | "dog" });

export interface Cat {
  petType: string;
  indoor?: boolean;
}

export interface Dog {
  petType: string;
}

export type Shape = Person | Labels;

export type MaybePerson = Person | null;

export type Event = {
  type: "created";
  at?: string;
} | {
  type: "deleted";
  reason: string;
};

export type Matrix = Array<number[]>;

export interface AccountRef {
  id: string;
  score?: number | null;
  firstTag?: string;
}

/**
 * Outer properties and required names apply to every variant.
 */
export type Feedback = {
  idempotencyKey: string;
  verdict: unknown;
} & ({
  verdict?: "up";
} | {
  verdict?: "down";
  reason: string;
});

export type Versioned = VersionOne | (VersionTwo & { schemaVersion: 2 });

export interface VersionOne {
  schemaVersion: 1;
}

export interface VersionTwo {
  schemaVersion: number;
}

export type Bare = (Cat & { petType: "Cat" | "cat" });

export type Inherited = Tabby;

export type Tabby = Cat & {
  stripes?: number;
};

export type NullableHolder = {
  inner?: {
    leaf?: string;
  } | null;
} | null;

export type Leaf = string;

export type Closed = { [key: string]: never };

export type Escapes = "a<b" | "x&y" | "quote\"d";

export interface ArrayType {
  value?: string;
}

export type MyType__2 = string;

export type MyType = number;

export type Default = string;
