// Code generated by libopenapi. DO NOT EDIT.

/**
 * A train station.
 */
export interface Station {
  id: string;
  name: string;
  address: string;
  country_code: string;
  timezone?: string;
}

/**
 * A train trip.
 */
export interface Trip {
  id?: string;
  origin?: string;
  destination?: string;
  departure_time?: string;
  arrival_time?: string;
  price?: number;
  bicycles_allowed?: boolean;
  dogs_allowed?: boolean;
}

/**
 * A booking for a train trip.
 */
export interface Booking {
  id?: string;
  trip_id?: string;
  passenger_name?: string;
  has_bicycle?: boolean;
  has_dog?: boolean;
}

/**
 * A payment for a booking.
 */
export interface BookingPayment {
  id?: string;
  amount?: number;
  currency?: "bam" | "bgn" | "chf" | "eur" | "gbp" | "nok" | "sek" | "try";
  /**
   * The payment source to take the payment from.
   */
  source?: {
    object?: "card";
    name: string;
    number: string;
    cvc: string;
    exp_month: number;
    exp_year: number;
    address_country: string;
  } | {
    object?: "bank_account";
    name: string;
    number: string;
    account_type: "individual" | "company";
    bank_name: string;
    country: string;
  };
  status?: "pending" | "succeeded" | "failed";
}
