openapi: 3.0
paths:
  /burgers:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nine'
components:
  schemas:
    One:
      description: "test one"
      properties:
        things:
          "$ref": "#/components/schemas/Two"
      required:
        - things
    Two:
      description: "test two"
      properties:
        testThing:
          "$ref": "#/components/schemas/One"
        anyOf:
          - "$ref": "#/components/schemas/Four"
      required:
        - testThing
        - anyOf
    Three:
      description: "test three"
      properties:
        tester:
          "$ref": "#/components/schemas/Four"
        bester:
          "$ref": "#/components/schemas/Seven"
        yester:
          "$ref": "#/components/schemas/Seven"
      required:
        - tester
        - bester
        - yester
    Four:
      description: "test four"
      properties:
        lemons:
          "$ref": "#/components/schemas/Nine"
      required:
        - lemons
    Five:
      properties:
        rice:
          "$ref": "#/components/schemas/Six"
      required:
        - rice
    Six:
      properties:
        mints:
          "$ref": "#/components/schemas/Nine"
      required:
        - mints
    Seven:
      properties:
        wow:
          "$ref": "#/components/schemas/Three"
      required:
        - wow
    Nine:
      description: done.
    Ten:
      properties:
        yeah:
          "$ref": "#/components/schemas/Ten"
      required:
        - yeah
