openapi: 3.1.0
components:
  schemas:
    Thing:
      type: object
      description: A thing that does nothing.
      properties:
        message:
          type: string
          description: I am pointless.