// Copyright 2022 Princess B33f Heavy Industries / Dave Shanley
// SPDX-License-Identifier: MIT

package v3

// Label definitions used to look up vales in yaml.Node tree.
const (
	ComponentsLabel        = "components"
	SchemasLabel           = "schemas"
	EncodingLabel          = "encoding"
	HeadersLabel           = "headers"
	ParametersLabel        = "parameters"
	RequestBodyLabel       = "requestBody"
	RequestBodiesLabel     = "requestBodies"
	ResponsesLabel         = "responses"
	CallbacksLabel         = "callbacks"
	ContentLabel           = "content"
	PathsLabel             = "paths"
	WebhooksLabel          = "webhooks"
	JSONSchemaDialectLabel = "jsonSchemaDialect"
	GetLabel               = "get"
	PostLabel              = "post"
	PatchLabel             = "patch"
	PutLabel               = "put"
	DeleteLabel            = "delete"
	OptionsLabel           = "options"
	HeadLabel              = "head"
	TraceLabel             = "trace"
	LinksLabel             = "links"
	DefaultLabel           = "default"
	SecurityLabel          = "security"
	SecuritySchemesLabel   = "securitySchemes"
	OAuthFlowsLabel        = "flows"
	VariablesLabel         = "variables"
	ServersLabel           = "servers"
	ServerLabel            = "server"
	ImplicitLabel          = "implicit"
	PasswordLabel          = "password"
	ClientCredentialsLabel = "clientCredentials"
	AuthorizationCodeLabel = "authorizationCode"
	DescriptionLabel       = "description"
	URLLabel               = "url"
	NameLabel              = "name"
	EmailLabel             = "email"
	TitleLabel             = "title"
	TermsOfServiceLabel    = "termsOfService"
	VersionLabel           = "version"
	LicenseLabel           = "license"
	ContactLabel           = "contact"
)
